### ISSUE TITLE
Update rubocop to latest (1.4.2)

### ISSUE THREAD

**Issue by magneticflux-** [jekyll/rubocop-jekyll#21]

**Comment by ashmaroli** [comment]
There is an open proposal to drop support for RuboCop versions older than v1.0 : #20
Once that ends up merged, I think updating to minor versions should be straight-forward

**Comment by mslinn** [comment]
No matter how I attempt to configure versions, I always get:
`Unable to activate rubocop-jekyll-0.12.0, because rubocop-1.26.0 conflicts with rubocop (~> 1.18.0)`

**.gemspec**
```
spec.add_development_dependency 'rubocop', '~> 1.18.0'
spec.add_development_dependency 'rubocop-jekyll'
```

Unless there is something else I can do when using Jekyll 4.2.2, `rubocop-jekyll` does not seem to be usable at present.

**Comment by parkr** [comment]
Follow https://github.com/jekyll/rubocop-jekyll/issues/30 for updates. Everything is ready to go to upgrade to 1.45.0, but I can't push the update. Hold tight!
