### ISSUE TITLE
Release v0.13.0

### ISSUE THREAD

**Issue by parkr** [jekyll/rubocop-jekyll#30]
I was seeing an error generated in https://github.com/jekyll/github-metadata/pull/245 and I wanted to upgrade the rubocop version. I was unable to since rubocop-jekyll locks rubocop to v1.18.0. I upgraded rubocop to lock it to v1.45.0 and tried to release/push but I don't have access to push the new gem and neither does jekyllbot.

@ashmaroli, would you mind releasing this version, v0.13.0?

**Comment by ashmaroli** [comment]
[`rubocop-jekyll-0.13.0`](https://rubygems.org/gems/rubocop-jekyll/versions/0.13.0) has been released.

**Comment by parkr** [comment]
Thank you! Would you consider adding jekyllbot as an owner to the gem so that it can push new releases? Let me know if you have any concerns.

**Comment by ashmaroli** [comment]
@parkr Sorry about that. I forgot about the bus factor.
I've sent requests to both you and Jekyllbot. Please check email accounts.

**Comment by ashmaroli** [comment]
TODO for ***v0.14.0***: Add `lib/rubocop/jekyll/version.rb`.

**Comment by parkr** [comment]
Done, thank you! And filed #31 for adding the version file. 😄
