### ISSUE TITLE
Add version.rb file to make compatible with release GitHub Action

### ISSUE THREAD

**Issue by parkr** [jekyll/rubocop-jekyll#31]
The release GitHub Action looks for changes to a `version.rb` file. We don't have one of those in this repo, so it will never run.

Noted by @ashmaroli here: https://github.com/jekyll/rubocop-jekyll/issues/30#issuecomment-1434967026

**Comment by ashmaroli** [comment]
Hello @parkr,
It looks like **Jekyllbot has not been configured to publish the cut gem** as per this [workflow log](https://github.com/jekyll/rubocop-jekyll/actions/runs/11483547648/job/31959233263).

(*API_KEY Environment Variable missing in repo settings*).

I have deleted the GitHub Tag and Release to facilitate a smooth workflow rerun.

**Comment by parkr** [comment]
@ashmaroli Added! It's `RUBYGEMS_GEM_PUSH_API_KEY` and should now be exposed to this repo.

**Comment by ashmaroli** [comment]
Thanks @parkr, will you be able to rerun the linked release workflow? I am not able to do so at the moment.
(Thanks in advance.)

*Update: I have rerun the workflow and published v0.14.*
